[package]
name = "health"
version = "1.0.0"
edition = "2021"

[dependencies]
config = "0.13.4"
lapin = "2.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sys-info = "0.9"

