name: Health CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: health  # Specify the path to the subdirectory
        ref: main     # The branch to checkout

    - name: Install Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build and test
      working-directory: health  # Set the working directory for subsequent steps
      run: |
        cargo build --verbose
        cargo test --verbose
