name: Health Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v3
      - name: "Test local rust"
        uses: Kristories/cargo-test@v1.0.0
        with:
          manifest-path: './health/Cargo.toml'
