name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: net/environment.yml

    - name: Activate Conda environment
      run: conda activate net


    # - name: Run tests
    #   run: |
    #     python -m unittest discover tests/

    # - name: Upload coverage
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: coverage
    #     path: .coverage
