name: Rust Build and Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  health:

    runs-on: ubuntu-latest

    steps:
    - name: Navigate to health
      run: cd health
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
